import localFont from "next/font/local";
import "./globals.css";
import { VisibilityProvider } from "@/context/VisibilityContext";

// Load custom fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Metadata for the app
export const metadata = {
  title: "SolaSolutions",
  description: "Generated by create next app",
};

// Single RootLayout function
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Wrap the entire app with VisibilityProvider */}
        <VisibilityProvider>{children}</VisibilityProvider>
      </body>
    </html>
  );
}
