import localFont from "next/font/local";
import "./globals.css";
import { VisibilityProvider } from "@/context/VisibilityContext";

// Load custom fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Add Nexa fonts with localFont
const nexaBlack = localFont({
  src: [
    { path: "./fonts/nexa-black.woff2", format: "woff2" },
    { path: "./fonts/nexa-black.woff", format: "woff" }
  ],
  variable: "--font-nexa-black",
  style: "normal",
  display: "swap",
});

const nexaBook = localFont({
  src: [
    { path: "./fonts/Nexa-Book.woff2", format: "woff2" },
    { path: "./fonts/Nexa-Book.woff", format: "woff" }
  ],
  variable: "--font-nexa-book",
  weight: "normal",
  style: "normal",
  display: "swap",
});

// Metadata for the app
export const metadata = {
  title: "solasolution",
  description: "Generated by create next app",
  icons: {
    icon: [
      { rel: "icon", url: '/favicon.ico', media: '(prefers-color-scheme: light)' },
      { rel: "icon", url: '/favicon.ico', media: '(prefers-color-scheme: dark)' }
    ]
  },
};

// Single RootLayout function
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${nexaBook.variable} antialiased`}
      >
        {/* Wrap the entire app with VisibilityProvider */}
        <VisibilityProvider>{children}</VisibilityProvider>
      </body>
    </html>
  );
}